### PR TITLE
add zpool scrub service

### PR DESCRIPTION
**Pull request by kdomanski**

### CODE REVIEW

**Comment by kdomanski** [comment]
@hinnerk @colszowka Every 12h might be too often. Please advise.

**Comment by colszowka** [comment]
Do we need some kind of error reporting output in the web UI?

**Comment by colszowka** [comment]
As to the frequency, I'd do it at most once per week, see i.e. https://forums.freebsd.org/threads/how-often-do-you-scrub.35663/

**Comment by kdomanski** [comment]
People in the thread report their scrubs to take many hours. Will the zpool be broken if a user hard-resets his machine during a scrub? Does the frequency of scrubs impact the time they take?

**Comment by hinnerk** [comment]
Scrubs are run in the background an can be interrupted and newly started without any ill effects. I'd suggest running them once a month at most. @kdomanski

**Pull request merged**
