### PR TITLE
use a copy of Samba's config dir for mounting inside the container

### PR DESCRIPTION
**Pull request by kdomanski**
this prevents soul's smbpasswd file from being chmodded to 600

/cc @colszowka

### CODE REVIEW

**Comment by colszowka** [comment]
Looking at https://github.com/experimental-platform/platform-configure/blob/development/services/smb-restart-protonet.path we will need to add an extra trigger restart trigger on either `/data/samba/etc/smbpasswd` or just replace the PathModified with the directory itself, which as per the systemd docs should work if I remember correctly

**Comment by colszowka** [comment]
Another thing that comes to my mind: Probably we should ensure the dir and files soul uses belong to 1000:1000 and have correct permissions on init-protonet, if only to clean up the boxes that we have now that will be broken with wrong permissions.

**Comment by hinnerk** [comment]
Yes, please add a `chown …` @kdomanski

**Comment by kdomanski** [comment]
`smbd` runs as root, so the ownership is irrelevant.

**Comment by colszowka** [comment]
@kdomanski I mean the soul side, we need to clean up the permissions on the soul-owned etc dir that got messed up by smbd on existing boxes

**Pull request merged**
